import express from "express";
import { getAllTools, getToolById, createTool, updateTool, deleteTool, assignTool, unassignTool } from "../controllers/toolsController.js";
const router = express.Router();
router.get("/", getAllTools);
router.get("/:id", getToolById);
router.post("/", createTool);
router.put("/:id", updateTool);
router.delete("/:id", deleteTool);
router.post("/:id/assign", assignTool);
router.post("/:id/unassign", unassignTool);
export default router;
